/**
 * Cloudflare Pages Middleware — Dynamic Rendering for Bots
 *
 * Regular users  → SPA (client-side React)
 * Bots / crawlers → pre-rendered static HTML snapshot
 *
 * The static HTML files are generated at build time by vite-plugin-prerender
 * and live alongside the SPA assets in the output directory.
 */

const BOT_AGENTS =
  /googlebot|google-extended|bingbot|yandex|baiduspider|twitterbot|facebookexternalhit|linkedinbot|slackbot|chatgpt-user|gptbot|claudebot|anthropic-ai|perplexitybot|applebot|duckduckbot|ia_archiver|rogerbot|embedly|showyoubot|outbrain|pinterestbot|quora link preview|redditbot|whatsapp|telegrambot|discordbot/i;

interface Env {
  ASSETS: { fetch: typeof fetch };
}

export const onRequest: PagesFunction<Env> = async (context) => {
  const ua = context.request.headers.get("user-agent") || "";
  const url = new URL(context.request.url);

  // Only intercept navigation requests (HTML pages), not assets
  const isPageRequest =
    !url.pathname.match(/\.\w{2,5}$/) || url.pathname.endsWith(".html");

  if (BOT_AGENTS.test(ua) && isPageRequest) {
    // Try to serve the prerendered HTML file for this route
    // e.g. /book → /book/index.html (generated by vite-plugin-prerender)
    const prerenderPath = url.pathname === "/" ? "/index.html" : `${url.pathname}/index.html`;
    const prerenderUrl = new URL(prerenderPath, url.origin);

    try {
      const prerenderResponse = await context.env.ASSETS.fetch(
        new Request(prerenderUrl.toString(), context.request)
      );

      if (prerenderResponse.ok) {
        return new Response(prerenderResponse.body, {
          status: 200,
          headers: {
            "Content-Type": "text/html; charset=utf-8",
            "X-Rendered-For": "bot",
            "Cache-Control": "public, max-age=3600",
          },
        });
      }
    } catch {
      // Fall through to SPA if prerendered file not found
    }
  }

  // Normal users (and bots without a prerendered page) get the SPA
  return context.next();
};
